
# **Worksheet - 1: Coding Exercise on Numpy.**

TO - DO - Task
Please complete all the problem listed below.

Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:

**1. Initialize an empty array with size 2X2.**

In [ ]:
import numpy as np
arr=np.zeros([2,2])
print(arr)

[[0. 0.]
 [0. 0.]]


**2. Initialize an all one array with size 4X2.**

In [ ]:
import numpy as np
arr=np.ones([4,2])
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [ ]:
import numpy as np
arr=np.full((2,2),3.14,dtype=float)
print(arr)

[[3.14 3.14]
 [3.14 3.14]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_arr = np.zeros_like(arr)
print(zeros_arr)


[[0 0 0]
 [0 0 0]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
ones_arr = np.ones_like(arr)
print(ones_arr)


[[1 1 1]
 [1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [ ]:
import numpy as np
new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(arr)


[1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

# Complete the following tasks:

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [ ]:
import numpy as np
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


**2. Create a 3X3 matrix with values ranging from 0 to 8.**
**{Hint:look for np.reshape()}**

In [ ]:
import numpy as np
arr = np.arange(9)
matrix = arr.reshape((3, 3))
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**

In [ ]:
import numpy as np
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.**
**# {Hint:check for np.random.random() and array.mean() function}**

In [ ]:
import numpy as np
ran=np.random.random(30)
m=ran.mean()
print(ran)
print(m)

[0.68226718 0.91974991 0.24566748 0.48445361 0.94010064 0.50434185
 0.68915644 0.2165949  0.91122659 0.98206923 0.87335988 0.78687989
 0.43315379 0.62722855 0.49029256 0.49709467 0.2855043  0.99846521
 0.11319716 0.49350736 0.71526897 0.49901228 0.95845809 0.1361169
 0.83946011 0.81228499 0.82123942 0.91210162 0.49770642 0.982908  ]
0.6449622673763606


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [ ]:
import numpy as np
random_values=np.random.random((10,10))
min_value=random_values.min()
max_value=random_values.max()
print(random_values)
print(min_value)
print(max_value)

[[7.72294702e-01 5.11395877e-01 3.95778567e-01 5.64484338e-04
  8.35741109e-01 4.09483099e-01 1.31401683e-01 2.94424378e-01
  2.18453854e-01 2.25254259e-01]
 [4.99209263e-02 9.01158459e-01 6.96064263e-01 7.70166006e-01
  4.17167329e-01 6.36637112e-01 2.18555797e-01 2.03466443e-01
  3.48465716e-01 5.01896926e-01]
 [8.69086691e-01 7.38716645e-01 5.30759687e-01 1.08038088e-02
  7.06856990e-01 7.40673624e-02 2.38176245e-01 7.50701206e-01
  5.74864805e-01 3.51503782e-01]
 [5.88059750e-01 3.45979208e-01 1.36900692e-01 4.52109252e-01
  8.82124822e-01 1.05701692e-01 9.50572863e-01 4.83074450e-01
  5.16508911e-01 9.19319673e-01]
 [9.76565985e-01 8.91270408e-01 2.05834504e-01 8.28499749e-01
  2.32200887e-01 7.26499096e-01 9.36031826e-01 8.48278553e-01
  9.56185750e-01 4.32831573e-01]
 [5.18608769e-01 3.41716451e-01 7.14562826e-01 2.34628165e-01
  7.23393732e-01 2.88681953e-01 5.97815054e-01 8.72871217e-01
  9.60590814e-01 3.72684290e-01]
 [9.97702212e-01 6.06631599e-01 6.35266124e-01 1.51155426e

**6. Create a zero array of size 10 and replace 5th element with 1.**

In [ ]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [ ]:
import numpy as np
arr=[1,2,0,0,4,0]
rev_arr=arr[::-1]
print(rev_arr)

[0, 4, 0, 0, 2, 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [ ]:
import numpy as np
rows, cols = 5, 5

arr = np.zeros((rows, cols), dtype=int)

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [ ]:
import numpy as np
rows,cols=8,8
arr=np.zeros((rows,cols),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:

For the following arrays:

**x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);**
**v = np.array([9,10]) and w = np.array([11,12]);**

Complete all the task using numpy:

1. Add the two array.

2. Subtract the two array.

3. Multiply the array with any integers of your choice.

4. Find the square of each element of the array.

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x-y)
print()
print(x-y)
print()
print(x*3)
print()
print(x**2)
print()
dot_vw=np.dot(v, w)
print(dot_vw)
print()
dot_xv=np.dot(x,v)
print(dot_xv)
print()
dot_xy=np.dot(x,y)
print(dot_xy)
print()
conc_xy=np.concatenate((x,y),axis=0)
print(conc_xy)
print()
conc_vw=np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print(conc_vw)
#concatenate of x and v shows error because NumPy cannot concatenate array of different dimensions

[[-4 -4]
 [-4 -3]]

[[-4 -4]
 [-4 -3]]

[[ 3  6]
 [ 9 15]]

[[ 1  4]
 [ 9 25]]

219

[29 77]

[[19 22]
 [50 58]]

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 11]
 [10 12]]


# **Problem - 4: Matrix Operations:**
• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

**1. Prove A.A−1 = I.**

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


**2. Prove AB ̸= BA.**

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)
print("AB == BA? ->", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB == BA? -> False


**3. Prove (AB)T = B T AT .**

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Equal? ->", np.array_equal(AB_T, BT_AT))


(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Equal? -> True


**• Solve the following system of Linear equation using Inverse Methods.**

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants matrix
B = np.array([-1, -3, 9])

# Find inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)
print(X)

[ 2.  1. -2.]
